#!/bin/sh
# Toggle synaptics touchpad

if [ $(synclient -l | grep TouchpadOff | awk '{print $3}') == 1 ] ; then
    synclient touchpadoff=0;
    ratpoison -c "echo Touchpad now enabled"
else
    synclient touchpadoff=1;
    ratpoison -c "echo Touchpad disabled"

fi
