#!/usr/bin/env bash

function print() {
        cat << EOF 

 #     #    #    ######  #     #   ###   #     #  #####

 #  #  #   # #   #     # ##    #    #    ##    # #     #

 #  #  #  #   #  #     # # #   #    #    # #   # #

 #  #  # #     # ######  #  #  #    #    #  #  # #  ####

 #  #  # ####### #   #   #   # #    #    #   # # #     #

 #  #  # #     # #    #  #    ##    #    #    ## #     #

  ## ##  #     # #     # #     #   ###   #     #  #####

 

                 THIS TERMINAL IS NOT A SECURE DEVICE

DO NOT PROCESS CLASSIFIED INFORMATION ON THIS EQUIPMENT AT ANY TIME!

 

- PROTECT user IDs, passwords, and computer telephone numbers.

- CONTROL access to your system.  Logout unattended systems.

- DESTROY classified and sensitive unclassified waste effectively.

- SAFEGUARD data, programs, procedures and documentation.

- ENSURE you have protected backup copies of data and software.

- DEFEND against computer viruses.  Never use unauthorized software.

- REPORT all security problems or violations immediately.

 

Unauthorized reproduction of copyrighted software is against the law.

**  This system is ONLY for official work by authorized personnel.

    Your automation security POC is - Ms.

       *     *     *     *     *     *     *     *     *
 
EOF
}; print

